### PR TITLE
BuildOro

### PR DESCRIPTION
**Pull request by joshuacode751**
New build I've tested maybe a slight FPS increase, Try 21# for performance with other games. If you have less fps on #21 use this build

### CODE REVIEW

**Comment by 00de214** [comment]
Around a 40% increase in framerate in Pokemon Scarlet when compared to the current master build.

**Comment by Serfrost** [comment]
I tested this in congested towns.  FPS Lows were brought up significantly.

- Prior build: 34-37
- Current: 44-47

This increase may be significantly more important on hardware lower than a R9 5600x @ 4.7GHz

**Comment by joshuacode751** [comment]
Added Latest Commit from PR##3748

**Comment by xXTheRussianXx** [comment]
Noticeable FPS bump on my Steam Deck compared to master; nasty white filter though.

**Comment by shade-sdev** [comment]
> white filter

I get white filter on LDN build too, did you find a fix?

**Comment by xXTheRussianXx** [comment]
> > white filter
> 
> I get white filter on LDN build too, did you find a fix?


So, yes and no. The 128-bit Discord dirty build, that uses PRs 3828 | 3754 | 2695 | 3830 | 3748, clears up almost all the visual problems for the Deck, no terrible filters - but the framerate is terrible. 

I was hoping when this dev implemented 3748 that was the fix we needed, but alas it was not. We continue to wait patiently.

**Comment by Serfrost** [comment]
It is probably best that you don't mention illicit Discord servers when this build is already mentioned in PR 3748's comment section. @joshuacode751 I'd recommend deleting whichever comments you see necessary (including this one.)

**Comment by joshuacode751** [comment]
> Noticeable FPS bump on my Steam Deck compared to master; nasty white filter though.

Try clearing shader cache?

**Comment by J66788777** [comment]
Avalonia doesn't work

**Comment by BearadactylPrime** [comment]
This build shows significant gains on several games that AMD struggled with, doubling performance in some games even. It can cause the odd graphical issue, like some objects outright not rendering or flickering in some games, however overall this build is excellent for AMD GPU/CPU combos in general.

My Hardware is specifically:
CPU: Ryzen 5 5600
GPU: Radeon RX 5700 XT 8GB Gigabyte OC
GPU Driver: 22.10.3
RAM: 32 GB DDR4 3200MHz
Mobo: ASROCK Pro4 B450m
OS: Windows 10

Hardware AA is also a very nice addition.

**Comment by DanielF823** [comment]
Very unusual - The VERY FIRST TIME I ran this on my Steam Deck it worked perfectly in Vulcan
Every Subsequent time (Even deleting Shader and Pipeline cache) it will have the white filter

**Comment by Mau094** [comment]
Hello. 
What would be the recommended configuration in graphic settings?

**Comment by Serfrost** [comment]
Will review shortly.

**Comment by Serfrost** [comment]
```
Master      [1.1.351]   Inside: 120~127   Outside: 57~62   SchoolPlaza: 36~39
#32 Test4   [9800df7]   Inside: 129~138   Outside: 64~81   SchoolPlaza: 48~53
#20 Oro     [81210ca]   Inside: 128~135   Outside: 64~81   SchoolPlaza: 47~52
```
Both Oro and Test4 appear to behave identically now within a margin of error.

**Comment by StevensND** [comment]
> ```
> Master      [1.1.351]   Inside: 120~127   Outside: 57~62   SchoolPlaza: 36~39
> #32 Test4   [9800df7]   Inside: 129~138   Outside: 64~81   SchoolPlaza: 48~53
> #20 Oro     [81210ca]   Inside: 128~135   Outside: 64~81   SchoolPlaza: 47~52
> ```
> 
> As of 11/16/22, both Oro #20 and [Test4](https://github.com/RyzenDew/Ryujinx/pull/32) now appear to behave identically within a margin of error -- granted, Test4 does not contain Post Processing options. Pick your poison.

Oro 20 works better for me compare to Test4, Test5 and Oro 21

**Comment by J66788777** [comment]
> ```
> Master      [1.1.351]   Inside: 120~127   Outside: 57~62   SchoolPlaza: 36~39
> #32 Test4   [9800df7]   Inside: 129~138   Outside: 64~81   SchoolPlaza: 48~53
> #20 Oro     [81210ca]   Inside: 128~135   Outside: 64~81   SchoolPlaza: 47~52
> ```
> 
> As of 11/16/22, both Oro #20 and [Test4](https://github.com/RyzenDew/Ryujinx/pull/32) now appear to behave identically within a margin of error -- granted, Test4 does not contain Post Processing options. Pick your poison.

Have you encountered the obnoxious graphical glitch when Macro HLE is enabled on Oro or Test 5? Test 4 does not have that issue

**Review by Simone-Andreotti — APPROVED** [review]

**Comment by joshuacode751** [comment]
REBASE

**Comment by pathetyk** [comment]
@joshuacode751 any idea why im unable to download this pull? it starts the download but does not progress at all.

**Comment by kamikazilucas** [comment]
when running pokemon violet at higher res the textures dont work properly

**Comment by MrSw4gGuy** [comment]
Why does this version have the upscale thing and the mainline don't? ;-;

**Comment by Serfrost** [comment]
> @kamikazilucas when running pokemon violet at higher res the textures dont work properly

This is a native issue in Mainline Master, not something that can be patched out with PRs that are currently available.

> @MrSw4gGuy Why does this version have the upscale thing and the mainline don't? ;-;

Post Processing (FXAA, SMAA, FSR) are a part of a pending PR and aren't a part of Mainline Master yet.

**Comment by joshuacode751** [comment]
Added PP changes from Riperiperi. Should make FXAA and SMAA Look better

**Comment by joshuacode751** [comment]
REBASE

**Comment by kamikazilucas** [comment]
> > @kamikazilucas when running pokemon violet at higher res the textures dont work properly
> 
> This is a native issue in Mainline Master, not something that can be patched out with PRs that are currently available.
> 
> > @MrSw4gGuy Why does this version have the upscale thing and the mainline don't? ;-;
> 
> Post Processing (FXAA, SMAA, FSR) are a part of a pending PR and aren't a part of Mainline Master yet.

ok can you tell me when mainline dosent have the issue anymore

**Comment by Serfrost** [comment]
> @kamikazilucas ok can you tell me when mainline dosent have the issue anymore

x2~x4 scaling is fixed in Mainline now.  Doesn't have Post Processing yet, that and the base PR for it needs patched; it has an incorrect offset which causes the output image to be much worse than it should be. (See SMAA Ultra)

**Comment by emausx12** [comment]
> > @kamikazilucas ok can you tell me when mainline dosent have the issue anymore
> 
> x2~x4 scaling is fixed in Mainline now. Doesn't have Post Processing yet, that and the base PR for it needs patched; it has an incorrect offset which causes the output image to be much worse than it should be. (See SMAA Ultra)

Anybody else finding the text looking a alot blurrier when upscaling to x2? Looks like it adds a AA filter on top of the text. After 1 year its still not fixed.

**Comment by kamikazilucas** [comment]
> > @kamikazilucas ok can you tell me when mainline dosent have the issue anymore
> 
> x2~x4 scaling is fixed in Mainline now. Doesn't have Post Processing yet, that and the base PR for it needs patched; it has an incorrect offset which causes the output image to be much worse than it should be. (See SMAA Ultra)

what is the post processing that needs to be added?

**Comment by joshuacode751** [comment]
rebase

**Comment by Lepplex** [comment]
The download link don't work

**Comment by sakuka47** [comment]
Lasted version  is great,  can you merge  Ryujinx.SDL2-CS to 2.26.0 #3894 ? For testing

**Comment by joshuacode751** [comment]
> Lasted version is great, can you merge Ryujinx.SDL2-CS to 2.26.0 [Ryujinx#3894](https://github.com/Ryujinx/Ryujinx/pull/3894) ? For testing

Merged, if there's a regression use the previous build.

**Comment by d3xMachina** [comment]
Please add [#3932](https://github.com/Ryujinx/Ryujinx/pull/3932) to fix the stats display on Vulkan.

**Comment by joshuacode751** [comment]
rebase

**Comment by Mick20012** [comment]
The recent merge updated https://github.com/Ryujinx/Ryujinx/pull/3932 too?

**Comment by KenJyn76** [comment]
Any chance you can merge [Ryujinx#2860](https://github.com/Ryujinx/Ryujinx/pull/2860)?

**Comment by jacky400** [comment]
Wonder what is the difference of this #20 and #21 ?

**Comment by joshuacode751** [comment]
> Wonder what is the major difference of this #20 and #21 PR?

21 has riperiperi:vk-buffer-migration branch merge. Its a branch that increases performance on games like Persona, Xenoblade and Hyrul Warriors. Some people said they have a slightly low fps when using that but It may be a placebo since it ran the same for me. But you can test it to see which build ran better for you thats why I have these two build made.

**Comment by xirtamehtsitahw** [comment]
I just attempted to use this build with the latest update of Pokémon Violet (1.1.0) and only succeeded in causing a crash following loading the game (game crashes right when you would normally gain control of your character).

**Comment by CauronRaven** [comment]
> I just attempted to use this build with the latest update of Pokémon Violet (1.1.0) and only succeeded in causing a crash following loading the game (game crashes right when you would normally gain control of your character).

Use 21# instead, been playing for weeks

**Pull request closed without merging**
